apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: develop
spec:
  destination:
    name: ''
    namespace: demo
    server: 'https://kubernetes.default.svc'
  source:
    path: develop
    repoURL: 'https://github.com/redsource03/infrastructure-demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
