apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
spec:
  destination:
    name: ''
    namespace: infra
    server: 'https://kubernetes.default.svc'
  source:
    path: infra
    repoURL: 'https://github.com/redsource03/infrastructure-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
