apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
        - name: elasticsearch-pv-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pv-claim
      containers:
      - name: elasticsearch
        image: elasticsearch:8.3.3
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: 'single-node'
        - name: xpack.security.enabled
          value: 'false'
        volumeMounts:
          - mountPath: "/usr/share/elasticsearch/data"
            name: elasticsearch-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: node-pv-03    