apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      volumes:
        - name: logstash-config-file
          configMap:
            name: logstash-configmap
      containers:
      - name: logstash
        image: logstash:8.3.3
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: logstash-config-file
          mountPath: /usr/share/logstash/config
        
---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: logstash-service
spec:
  type: LoadBalancer
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000