apiVersion: v1
data:
  logstash.conf : |
    input {
        beats {
          port => 5044
        }
      }

      filter {
        mutate {
          add_tag => [ "logstash_filter_applied" ]
        }
      }

      output {
        elasticsearch {
          hosts => "elastisearch-service.infra.svc.cluster.local:9200"
        }
      }
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-07T09:03:55Z"
  name: logstash-configmap
  namespace: infra