apiVersion: v1
data:
  logstash.conf : |
    input {
          udp {
              port => "5000"
              type => syslog
              codec => json
          }
          tcp {
              port => "5000"
              type => syslog
              codec => json_lines
          }
          http {
              port => "5001"
              codec => "json"
          }
      }

      filter {
        mutate {
          add_tag => [ "logstash_filter_applied" ]
        }
      }
      output {
        elasticsearch { hosts => ["elastisearch-service.infra.svc.cluster.local:9200] }
        stdout { codec => rubydebug }
      }
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-07T09:03:55Z"
  name: logstash-configmap
  namespace: infra