apiVersion: v1
data:
  charset.cnf: |
  input {
    udp {
        port => "5000"
        type => syslog
        codec => json
    }
    tcp {
        port => "5000"
        type => syslog
        codec => json_lines
    }
    http {
        port => "5001"
        codec => "json"
    }
  }

  filter {
      if [type] == "syslog" {
          mutate {
              add_field => { "instance_name" => "%{app_name}-%{host}:%{app_port}" }
          }
      }
  }

  output {
      elasticsearch {
          hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
          index => "logs-%{+YYYY.MM.dd}"
      }
  }


kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: infra