apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: team1
  name: springboot-app1
  labels:
    app: springboot-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app1
  template:
    metadata:
      labels:
        app: springboot-app1
    spec:
      containers:
      - name: springboot-app1
        image: redsource/springboot-app1:1.0.0-740a43c2e4d5
        ports:
        - containerPort: 8080
        env:
        - name: LOGSTASH_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: logstash-url
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: kafka-url
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: mongo-user
        - name: MONGO_PW
          valueFrom:
            secretKeyRef:
              name: secret
              key: mongo-password
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: springboot-app1-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-app1
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
---